// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACQ5wy-5ad3bosJLfpq8bAbowAGcfG15A',
    appId: '1:591879372067:web:0161ad150a9bd195dc6096',
    messagingSenderId: '591879372067',
    projectId: 'ernlen',
    authDomain: 'ernlen.firebaseapp.com',
    storageBucket: 'ernlen.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhOfaq9-8PonwulmNcKhf9ZacoaGLZKs0',
    appId: '1:591879372067:android:8592b400b56411a4dc6096',
    messagingSenderId: '591879372067',
    projectId: 'ernlen',
    storageBucket: 'ernlen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfySE44QMpBwA69OoajQJXzyEBTt7KLP8',
    appId: '1:591879372067:ios:4c682495392fdd07dc6096',
    messagingSenderId: '591879372067',
    projectId: 'ernlen',
    storageBucket: 'ernlen.appspot.com',
    iosBundleId: 'com.example.ernlen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfySE44QMpBwA69OoajQJXzyEBTt7KLP8',
    appId: '1:591879372067:ios:4c682495392fdd07dc6096',
    messagingSenderId: '591879372067',
    projectId: 'ernlen',
    storageBucket: 'ernlen.appspot.com',
    iosBundleId: 'com.example.ernlen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACQ5wy-5ad3bosJLfpq8bAbowAGcfG15A',
    appId: '1:591879372067:web:1459067d672c5ad4dc6096',
    messagingSenderId: '591879372067',
    projectId: 'ernlen',
    authDomain: 'ernlen.firebaseapp.com',
    storageBucket: 'ernlen.appspot.com',
  );
}
